[package]
name = "frontend"
version = "0.1.0"
authors = ["Phlana <joshua.chang422@gmail.com>"]
edition = "2018"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
yew = { version = "0.13.0", features = ["std_web"] }

